---
- name: apt | install apt packages
  #sudo: yes
  apt: name={{ item }} state=present
  with_items:
   - avahi-daemon # for easier access - ssh root@marina.local
   - git-core
   - docker.io
  tags:
   - marina
   - packages
