marina:
  hostname: "{{lookup('env','MARINA_HOSTNAME') | default('marina')}}"
  repo:
    branch: master
    url: "https://github.com/cloudfleet/marina.git"
  home: "{{ansible_env.HOME}}"
  src: "{{ansible_env.HOME}}/marina"
  security: "{{ansible_env.HOME}}/security"
  dh_size: "{{lookup('env','DH_SIZE') | default('512')}}"
  # 512 for development purposes - use 2048 in production
  registry:
    user: "{{lookup('env','REG_USER') | default('test')}}"
    pw: "{{lookup('env','REG_PW') | default('testpw')}}"
    email: "{{lookup('env','REG_EMAIL') | default('test@example.com')}}"
    domain: "{{lookup('env','REG_DOMAIN') | default('registry.marina.io')}}"
