---
- name: schedule | cron job for building images
  # Ensure a job that runs at 2 exists.
  cron:
    name: "build images"
    minute: "0"
    hour: "2"
    job: "{{ marina.src }}/scripts/build_docker_images.sh {{ marina.src }}/scripts/docker_images.txt {{ marina.home }}/docker_images"
  tags:
    - marina
    - schedule

- name: schedule | cron job for pushing images
  cron:
    name: "push images"
    minute: "0"
    hour: "3"
    job: "{{ marina.src }}/scripts/push_docker_images.sh {{ marina.src }}/scripts/docker_images.txt {{ marina.registry.user }} {{ marina.registry.pw }} {{ marina.registry.email }} {{ marina.registry.domain }}"
  tags:
    - marina
    - schedule
